website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, AlumniScholarProfiles, Events, Careers
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

# Admin route
@auth.route('/admin')
def admin():
    total_users = User.query.all()
    return render_template("admin.html", user=current_user)

# Login route
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')  
         
        # Check if user exists in the database
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else: 
            flash('Account does not exist. Create a new account', category='error')
    return render_template("login.html", user=current_user)

# Logout route
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# Signup route
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        password = request.form.get('password')
        password2 = request.form.get('password2')
        
        user = User.query.filter_by(email=email).first()
        print(user)
        # Check if email already exists in the database
        if user:
            flash('Email already exists', category='error')    
              
        # Validate form inputs
        elif len(email) < 4:
            flash('Invalid email!', category='error') 
        elif len(firstname) < 2:
            flash('Name must be more than 2 characters!', category='error') 
        elif len(lastname) < 2:
            flash('Name must be more than 2 characters!', category='error') 
        elif password != password2:
            flash('Passwords do not match!', category='error') 
            
        # Create new user and add to database
        else: 
            new_user = User(
                email=email, 
                firstname=firstname,
                lastname=lastname,
                password=generate_password_hash(password, method='sha256')
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True, force=True) 
            flash('Account created successfully!',category='success')
            
            return redirect(url_for('auth.create_profile')) 
    
    return render_template("signup.html", user=current_user)

# Create profile route
@auth.route('/create-profile', methods=['GET', 'POST'])
@login_required
def create_profile():  
    if request.method  == 'POST':
        scholars_code = request.form.get('scholarsCode')
        primary_number = request.form.get('primaryNumber')
        secondary_number = request.form.get('secondaryNumber')
        country = request.form.get('country')
        home_county = request.form.get('homeCounty')
        current_county = request.form.get('currentCounty')
        equity_home_branch = request.form.get('Equity-home-branch')
        school_university_college = request.form.get('schoolUniversity')
        course = request.form.get('course')
        interests = request.form.get('interests')
        hobbies = request.form.get('hobbies') 
        # 
        new_profile = AlumniScholarProfiles (
            user_id = current_user.id,
            scholars_code=scholars_code,
            primary_number=primary_number,
            secondary_number=secondary_number,
            country=country,
            home_county=home_county,
            current_county=current_county,
            equity_home_branch=equity_home_branch,
            school_university_college=school_university_college,
            course=course,
            interests=interests,
            hobbies=hobbies      
        )
        # Adding new profile to the database
        db.session.add(new_profile)
        db.session.commit()    
        flash('Profile created successfully!',category='success') 
        return redirect(url_for('views.home'))
               
    return render_template('create_profile.html', user=current_user)

website/views.py
from flask import Blueprint, render_template, url_for, request, flash, jsonify, redirect
from flask_login import login_required,  current_user
from flask_wtf.csrf import generate_csrf
from .models import User, Note,AlumniScholarProfiles, Events, Careers
from . import db
from datetime import datetime
import json

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'] )
def home():
    # if request.method == 'POST':
    #     note = request.form.get('note')
        
    #     if len(note) < 1:
    #         flash('Note is too short', category='error')
    #     else:
    #         new_note = Note(data=note, user_id=current_user.id)
    #         db.session.add(new_note)
    #         db.session.commit()
    #         flash("Note added!", category='success') 
    return render_template("home.html", user=current_user)

@views.route('/about')
def about():
    return render_template("about.html", user=current_user)



@views.route('/events', methods=['GET', 'POST'])
def events():
    events = Events.query.order_by(Events.event_date.asc()).all()
    return render_template("events.html", user=current_user, events=events)

@views.route('/create-event', methods=['GET', 'POST'])
@login_required
def create_event():
    if request.method == 'POST':
        event = Events(
            user_id=current_user.id,
            event_name=request.form.get('event_name'),
            event_venue=request.form.get('event_venue'),
            event_date=datetime.strptime(request.form.get('event_date'), '%Y-%m-%dT%H:%M') if request.form.get('event_date') else None,
            event_description=request.form.get('event_description'),
            phone_number=request.form.get('phone_number'),
            email=request.form.get('email')
        )
        db.session.add(event)
        db.session.commit()
        flash('Your event has been created!', 'success')
        return redirect(url_for('views.events'))
    csrf_token = generate_csrf()
    return render_template("create_event.html", user=current_user, csrf_token=csrf_token)


@views.route('/careers')
def careers():
    careers = Careers.query.order_by(Careers.date_published.asc()).all()
    
    return render_template("careers.html", user=current_user, careers=careers)

@views.route('/create-job-listing', methods=['GET', 'POST'])
def create_job_listing():
    if request.method == 'POST':
        career = Careers(
            user_id=current_user.id,
            job_title=request.form.get('job_title'),
            company=request.form.get('company'),
            location=request.form.get('location'),
            salary=request.form.get('salary'),
            deadline_date=request.form.get('dealine_date'),
            job_description=request.form.get('job_description'),
            phone_number=request.form.get('phone_number'),
            email=request.form.get('email')
        )
        db.session.add(career)
        db.session.commit()
        flash('Your job listing has been created!', 'success')
        return redirect(url_for('views.careers'))
    return render_template("create_job.html", user=current_user)


@views.route('/find-alumni', methods=['GET', 'POST'])
def find_alumni():
    scholars = User.query.order_by(User.firstname.asc()).all()
    # scholar_profiles = [scholar.profile for scholar in scholars]
    return render_template("find_alumni.html", user=current_user, scholars=scholars)


@views.route('/delete-note', methods=["POST"])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note: 
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()
   
    return jsonify({})

website/templates/about.html
{% extends "base.html" %}
{% block title %}
Alumni Connect|About
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 30px; max-width: 900px;">
    <div>
        <h1 class="sub-title">Equity Group Holdings Company</h1>
        <p class="body-text">Equity Group Holdings Limited is a financial services holding company based in Kenya. It was founded in 1984 by James Mwangi as Equity Building Society, a small microfinance institution, and has since grown into one of the largest financial services providers in East Africa.

            Equity Group Holdings operates in six African countries: Kenya, Uganda, Tanzania, Rwanda, South Sudan, and the Democratic Republic of Congo. It offers a range of financial services including banking, insurance, investment banking, and asset management.
            
            In recent years, Equity Group Holdings has been recognized for its innovative approach to financial inclusion, particularly through its use of mobile technology to provide access to banking services to previously unbanked populations. The company has also been committed to social and environmental sustainability, with initiatives focused on education, health, and the environment.
            
            As of 2021, Equity Group Holdings had over 14.5 million customers and total assets of over Kshs 1.1 trillion (approximately USD 10 billion). It is listed on the Nairobi Securities Exchange and the Uganda Securities Exchange.
            <p>
    </div>

    <div>
        <h1 class="sub-title">Equity Wings To Fly Program</h1>
        <p class="body-text">
            Equity Wings to Fly Program is a scholarship program that was established in 2010 by Equity Group Holdings Limited in partnership with the Mastercard Foundation and other partners. The program aims to provide comprehensive secondary school scholarships and leadership training to academically gifted but financially challenged students in Kenya.

            The program targets bright and needy students who have scored at least 350 marks in their Kenya Certificate of Primary Education (KCPE) exams. The scholarship covers tuition fees, books, uniforms, and boarding facilities for the entire four-year secondary school education. The program also provides mentorship, leadership training, and career guidance to the beneficiaries.

            Since its inception, the program has awarded scholarships to over 20,000 students, with a goal of supporting 10,000 students every year. The program has also achieved a high success rate, with over 90% of its graduates joining universities, colleges, or other tertiary institutions.

            The Equity Wings to Fly program has been recognized as a leading initiative in education and social impact, winning several awards, including the East Africa Philanthropy Award and the FT/IFC Transformational Business Awards. It has also contributed to Equity Group Holdings' reputation as a socially responsible company that is committed to providing access to education and financial services to underserved communities.

           
        <p>
    </div>

    <div>
        <h1 class="sub-title">Equity Leadership Program</h1>
        <p class="body-text text-center">
            The Equity Leadership Program is a leadership development initiative offered by Equity Group Holdings Limited, one of the largest financial services providers in East Africa. The program is designed to develop leadership skills and capabilities among young professionals in the financial sector and other industries.

            The program targets young professionals who have demonstrated exceptional leadership potential and a commitment to excellence. The program is open to candidates from all nationalities and backgrounds, and participants are selected through a competitive application and interview process.

            The program is a one-year course that combines both classroom and experiential learning. The curriculum covers topics such as leadership theory, organizational behavior, strategic planning, and financial management. Participants also engage in mentorship, coaching, and networking opportunities with industry leaders and experts.

            The program aims to develop a new generation of leaders who are equipped with the skills, knowledge, and values necessary to drive innovation, growth, and sustainability in their organizations and communities. The program has a strong emphasis on social responsibility and ethical leadership, reflecting Equity Group Holdings' commitment to creating positive social and environmental impact.

            Since its inception, the Equity Leadership Program has produced over 300 graduates, many of whom have gone on to assume leadership positions in the financial sector, government, and other industries. The program has been recognized for its impact and innovation, winning several awards, including the Best Leadership Development Program at the HR Summit Awards.
        <p>
    </div>

</div>


{% endblock %}

website/templates/admin.html
{% extends 'base.html' %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="#">
                <span data-feather="home"></span>
                Dashboard <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file"></span>
                Groups
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="shopping-cart"></span>
                events
              </a>
            </li>
          </ul>

          <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
            <span>Interaction reports</span>
            <a class="d-flex align-items-center text-muted" href="#">
              <span data-feather="plus-circle"></span>
            </a>
          </h6>
          <ul class="nav flex-column mb-2">
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Current month
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">
                <span data-feather="file-text"></span>
                Past year
              </a>
            </li>
          </ul>
        </div>
      </nav>



<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
  <div></div>
    
</main>
    </div>
  </div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.css">
    <script
    defer
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
    <script
    defer
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script
    defer
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
    <script 
    defer
    src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.29.0/feather.min.js" integrity="sha512-24XP4a9KVoIinPFUbcnjIjAjtS59PUoxQj3GNVpWc86bCqPuy3YxAcxJrxFCxXe4GHtAumCbO2Ze2bddtuxaRw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js">feather.replace()</script>


  <link rel="shortcut icon"  href="{{ url_for('static', filename='images/equity-bank-logo.png') }}"/>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <title>{% block title %}{% endblock %}</title>
    <script type="text/javascript" src="{{url_for('static', filename='index.js')}}" defer></script>
</head>
<body>
<nav class="navbar navbar-expand-lg">
    <div class="container nav-container d-flex flex-row">
        
        <div class="logo" >
            <a href="{{url_for('views.home')}}">
            <img id="logo-image" src="{{url_for('static', filename='images/equity-bank-logo.png')}}">
            </a>
        </div>
        <button class="navbar-toggler text-right" type="button" data-toggle="collapse" data-target='#navbar'>
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}">Home</a>
                <a class="nav-item nav-link" id="about" href="{{url_for('views.about')}}">About</a>
                <a class="nav-item nav-link" id="events" href="{{url_for('views.events')}} ">Events</a>
                <a class="nav-item nav-link" id="careers" href="{{url_for('views.careers')}}">Careers</a>
                <a class="nav-item nav-link" id="find-alumni" href="{{url_for('views.find_alumni')}}">Find Alumni</a>
                <a class="nav-item nav-link" id="logout" href="{{url_for('auth.logout')}}">Logout</a>
                {% else %}  
                <a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}">Home</a>
                <a class="nav-item nav-link" id="about" href="{{url_for('views.about')}}">About</a>
                <a class="nav-item nav-link" id="events" href="{{url_for('views.events')}}">Events</a>
                <a class="nav-item nav-link" id="careers" href="{{url_for('views.careers')}}">Careers</a>
                <a class="nav-item nav-link" id="find-alumni" href="{{url_for('views.find_alumni')}}">Find Alumni</a>
                <a class="nav-item nav-link" id="login" href="{{url_for('auth.login')}}">Login</a>     
                <a class="nav-item nav-link" id="signup" href="{{url_for('auth.signup')}}">Signup</a>
                {% endif %}
            </div>
        </div>
        
        
    </div>
</nav>
 
{% with messages = get_flashed_messages(with_categories=true)%}
{% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
{% endif %}
{% endwith%}

{% block content%}
{% endblock %}


<footer>
    <div id="footer">
        <hr/>
        <div class="container flex-column">        
            <p>Contacts</p>
            <p>info@equitygroupholdings.com<p>
            <p>Tel: +254 763 000 000</p>
        </div>
        <p class="text-center align-self-end pt-5">Copyright 2023 @equitygroupholdings.com</p>
    </div>
</footer>
  
</body>
</html>

website/templates/careers.html
{% extends "base.html" %}
{% block title %}
Equity Alumni Connect|Events
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
    <div class="col-md-2 d-none d-md-block bg-light sidebar-wrapper">
        <div class="position-sticky sticky-top">
        <nav class="bg-light sidebar">
            <!-- Events sidebar -->
            <div class="sidebar-sticky">
            <form class="sidebar-search" action="" method="POST">
                <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                </div>
                <input type="text" class="form-control" placeholder="Search...">
                <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </form>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Job categories</span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Engineering
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Medical
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        Business Related
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('views.create_job_listing')}}">
                        Create a Job Listing
                    </a>
                </li>
            </ul>
            </div>
        </nav>
        </div>
    </div>

    <main role="main" class="col-md-10 px-4">
        <div class="container">
        <h1 class="mt-3 mb-5">Browse all opportunities</h1>

        <style>
            .job-card {
                background-color: rgba(130, 39, 27, 0.09);
                box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
                max-width: 800px;
                min-height: 250px;
                padding-top: 10px;
                padding-bottom: 10px;
                margin-bottom: 20px
            }
            .job-card  a {
                margin-left: auto;
                margin-right: auto;
            }
            .profile-picture {
                
                
            }
            .profile-picture img {
                width: 80px;
                height: 80px;
                border: 4px solid #A32A29;
                border-radius: 50%;
                object-fit:cover;
                
            }
        </style>
        {% for career in careers %}
        <div class="row nowrap job-card " style="margin: 10px">
            <div class="row mt-2">
                <h3 class="col-6 sub-title">{{career.job_title}}</h3>
                <h3 class="col-6 mb-3 sub-title" style="font-weight: 200;" >{{career.company}}</h3>
            </div>
            <div class="row mt-2 body-text">
                <div class="col-3">
                    <h5 >Location</h5>
                    <span>{{career.location}}</span>
                </div>
                <div class="col-3">
                    <h5 >Deadline</h5>
                    <span>{{career.deadline_date}}</span>
                </div>
                <div class="col-3">
                    <h5 >Salary</h5>
                    <span>{{career.salary}}</span>
                </div>
                <div class="col-3">
                    <h5 >Views</h5>
                    <span>-</span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-2 profile-picture">
                    <img class="img-fluid " src="{{url_for('static', filename='images/event-1.jpg')}}"> 
                </div>
                <div class="col-5 pt-2">
                    <h6>{{user.firstname}} {{user.lastname}}</h6>
                    <span>Published: {{career.date_published}}</date>
                </div>
            </div>
            <div class="row align-center">
                <a href="#" class="text-center" style="text-decoration: none; font-weight: bold; color:#A32A29">View Details</a>
            </div>
        </div>
        {% endfor %}
        
        
        
        </div>
    </main>
    </div>
</div>
  
{% endblock %}

website/templates/events.html
{% extends "base.html" %}
{% block title %}
Equity Alumni Connect|Events
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row">
    <div class="col-md-2 d-none d-md-block bg-light sidebar-wrapper">
        <div class="position-sticky sticky-top">
        <nav class="bg-light sidebar">
            <!-- Events sidebar -->
            <div class="sidebar-sticky">
            <form class="sidebar-search" action="" method="POST">
                <div class="input-group">
                <input type="text" class="form-control" placeholder="Search...">
                <button class="btn btn-primary" type="submit">
                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                </button>
                </div>
            </form>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                <span>Event categories</span>
                <a class="d-flex align-items-center text-muted" href="#">
                </a>
            </h6>
            <ul class="nav flex-column">
                <li class="nav-item">
                <a class="nav-link active" href="#">
                    Create event
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="#">
                    Upcoming event
                </a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.create_event')}}">
                    Past events
                </a>
                </li>
            </ul>
            </div>
        </nav>
        </div>
    </div>

    <main role="main" class="col-md-10 px-4">
        <div class="container">
        <h1 class="mt-3 mb-5">Browse all Events</h1>

        <style>
            .event-page-card {
                background-color: rgba(130, 39, 27, 0.09);
                box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.2);
                max-width: 900px;
                min-height: 250px;
                padding-top: 10px;
                padding-bottom: 10px;
                margin-bottom: 20px
            }
            .event-page-card  a {
                margin-left: auto;
                margin-right: auto;
                padding: 30px;
            }
        </style>
        {%if events %}
        <h1 class="mt-3 mb-5">See all Alumni/scholars available</h1>
        {% for event in events %}
        <div class="row d-flex flex-row flex-wrao event-page-card" style="">
            <div class="col-md-6 col-sm-4" style="width: 50%">
                <img src="{{url_for('static', filename='images/event-1.jpg')}}" alt="event one image" style="width: 100%; height: 230px; object-fit:cover;">
            </div>

            <div class="col-md-6 col-sm-8 align-center" style="width:50%;">
                <h2>{{ event.event_name }}</h2>
                <p>{{event.event_description[:150]}}...</p>
                <p>Date: {{event.event_date}}</p>
                <p>Venue: {{event.event_venue}}</p>

                <a href="#" class="text-center" style="text-decoration: none; font-weight: bold; color:#A32A29; font-size: 1.2rem">View Event</a>
            </div>
        </div>{% endfor %}
        {% endif %} 
        
        
        </div>
    </main>
    </div>
</div>
  
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}
Login|Equity Alumni Connect
{% endblock %}

{% block content %}
<div class="container align-center m-5 signup-form">
    <form class="form" method="POST">
        <h2>Log In to continue to Equity Alumni Connect</h2>
        <div class="form-group">
            <label for="email">Email</label>
            <input id="email" class="form-control" name="email" type="email" placeholder="Enter email" required>
        </div>
        
        <div class="form-group">
            <label for="password">Password</label>
            <input id="password" class="form-control" name="password" type="password" placeholder="Enter password" required>
        </div>
        
        <input type="submit" class="btn btn-primary ">
        <p class="mt-5">Don't have an account? <a href="{{url_for('auth.signup')}}">Sign Up here</a></p>
    </form>
</div>
{% endblock %}